stages:
  train:
    cmd: python src/PetCare.py
    deps:
    - src
    - ds

params:
- params.yaml
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  model:
    path: model.keras
    type: model
    desc: model
